module.exports = [
  'A Heavenly Affair',
  'Abba Zaba',
  'Adams and Brooks',
  'Advent Calendars',
  'Aero Bar',
  'After Dinner Mints',
  'After Eight',
  'AirHeads',
  'AirHeads Bites',
  'AirHeads Bulk',
  'AirHeads Gummies',
  'AirHeads Lollipops',
  'AirHeads Mini Bars',
  'AirHeads Xtremes',
  'Albanese Chocolate',
  'Albanese Confectionery',
  'Albanese Fruit Slices',
  'Albanese Gummy Bears',
  'Albanese Gummy Worms',
  'Albanese Rings',
  'Albanese Sour Gummy Bears',
  'Albanese Sour Gummy Worms',
  "Albert's Candy",
  'Aldama',
  'Alien Shaped Candy',
  'Alligator Shaped Candy',
  'Allsorts',
  'Almond Joy',
  'Almond Roca',
  'Almonds',
  'Altoids',
  'Amarula',
  'American Carnival Mart',
  'American Fish',
  'American Licorice Company',
  'American Metalcraft',
  'Amos Sweets',
  'Amport Foods',
  'Anahuac',
  'Anchor Hocking',
  'Andes Mints',
  'Angelitos',
  'Animal',
  'Animal Shaped Candy',
  'Annabelle Candy Company',
  'Anthon Berg',
  'Ants',
  'Apple Candy',
  'Apple Shaped Candy',
  'Applehead',
  'Archie McPhee',
  'Arcor',
  'Arway Confections',
  'Asbach Uralt',
  "Asher's Chocolate Almond Bark",
  "Asher's Chocolate Cherry Cordials",
  "Asher's Chocolate Clusters",
  "Asher's Chocolate Covered Graham Crackers",
  "Asher's Chocolate Covered Peanut Butter Cups",
  "Asher's Chocolate Covered Potato Chips",
  "Asher's Chocolate Covered Pretzels",
  "Asher's Chocolate Nonpareils",
  "Asher's Chocolates",
  "Asher's Sugar Free Chocolate",
  "Asher's Taffy",
  'Asian Candy',
  'Assorted Candy',
  'Assorted Candy Sticks',
  'Assorted Dum Dums',
  'Assorted Espeez',
  'Assorted Jelly Belly',
  'Assorted Licorice',
  'Astro Pop',
  'Atkinson Candy',
  'Atomic FireBall',
  "Au'some",
  'Australian Candy',
  'BB Bats',
  'BROOKSIDE',
  'BaBa Candy',
  'Baby Bottle Pop',
  'Baby Ruth',
  'Baby Shower',
  'Bachelorette Party',
  'Back to School',
  'Bacon Candy',
  'Bags',
  'Bakers Candies',
  "Bali's Best",
  "Bali's Best Coffee Candy",
  "Bali's Best Espresso Candy",
  "Bali's Best Tea Candy",
  'Balloon Shaped Candy',
  'Balloons',
  'Banana Candy',
  'Banana Shaped Candy',
  'Banana Taffy',
  'Bananarama',
  'Baptism',
]
