module.exports = [
  'A Heavenly Affair',
  'Abba Zaba',
  'Adams and Brooks',
  'Advent Calendars',
  'Aero Bar',
  'After Dinner Mints',
  'After Eight',
  'AirHeads',
  'AirHeads Bites',
  'AirHeads Bulk',
  'AirHeads Gummies',
  'AirHeads Lollipops',
  'AirHeads Mini Bars',
  'AirHeads Xtremes',
  'Albanese Chocolate',
  'Albanese Confectionery',
  'Albanese Fruit Slices',
  'Albanese Gummy Bears',
  'Albanese Gummy Worms',
  'Albanese Rings',
  'Albanese Sour Gummy Bears',
  'Albanese Sour Gummy Worms',
  "Albert's Candy",
  'Aldama',
  'Alien Shaped Candy',
  'Alligator Shaped Candy',
  'Allsorts',
  'Almond Joy',
  'Almond Roca',
  'Almonds',
  'Altoids',
  'Amarula',
  'American Carnival Mart',
  'American Fish',
  'American Licorice Company',
  'American Metalcraft',
  'Amos Sweets',
  'Amport Foods',
  'Anahuac',
  'Anchor Hocking',
  'Andes Mints',
  'Angelitos',
  'Animal',
  'Animal Shaped Candy',
  'Annabelle Candy Company',
  'Anthon Berg',
  'Ants',
  'Apple Candy',
  'Apple Shaped Candy',
  'Applehead',
  'Archie McPhee',
  'Arcor',
  'Arway Confections',
  'Asbach Uralt',
  "Asher's Chocolate Almond Bark",
  "Asher's Chocolate Cherry Cordials",
  "Asher's Chocolate Clusters",
  "Asher's Chocolate Covered Graham Crackers",
  "Asher's Chocolate Covered Peanut Butter Cups",
  "Asher's Chocolate Covered Potato Chips",
  "Asher's Chocolate Covered Pretzels",
  "Asher's Chocolate Nonpareils",
  "Asher's Chocolates",
  "Asher's Sugar Free Chocolate",
  "Asher's Taffy",
  'Asian Candy',
  'Assorted Candy',
  'Assorted Candy Sticks',
  'Assorted Dum Dums',
  'Assorted Espeez',
  'Assorted Jelly Belly',
  'Assorted Licorice',
  'Astro Pop',
  'Atkinson Candy',
  'Atomic FireBall',
  "Au'some",
  'Australian Candy',
  'BB Bats',
  'BROOKSIDE',
  'BaBa Candy',
  'Baby Bottle Pop',
  'Baby Ruth',
  'Baby Shower',
  'Bachelorette Party',
  'Back to School',
  'Bacon Candy',
  'Bags',
  'Bakers Candies',
  "Bali's Best",
  "Bali's Best Coffee Candy",
  "Bali's Best Espresso Candy",
  "Bali's Best Tea Candy",
  'Balloon Shaped Candy',
  'Balloons',
  'Banana Candy',
  'Banana Shaped Candy',
  'Banana Taffy',
  'Bananarama',
  'Baptism',
  'Bar & Bat Mitzvah',
  'Bar Mitzvah Candy - Blue',
  'BarNone',
  'Barcel USA',
  'Barenland',
  'Barnier',
  'Barrels of Yum',
  'Bartons Candy',
  'Baseball',
  'Baseball Shaped Candy',
  'Basketball',
  'Basketball Shaped Candy',
  'Baskin Robbins',
  'Bat Mitzvah Candy - Pink',
  'Bazooka Gum',
  'Beach & Luau',
  'Bear Creek Smokehouse',
  'Bear Shaped Candy',
  'Bears',
  'Bee International Inc',
  'Beemans Gum',
  'Belgian Candy',
  'Beny',
  'Beverages',
  'Biermann Marzipan',
  'Big BIG Gummy Bear',
  'Big Hunk',
  'Big League Chew',
  'Big Little Fudge',
  'Big Red',
  'Bird Shaped Candy',
  'Birthday',
  'Bissingers',
  'Bit-O-Honey',
  'Bite Size',
  'Black Candy',
  'Black Cow',
  'Black Espeez',
  'Black Forest',
  'Black Forest Fruit Snacks',
  'Black Forest Gummy Bears',
  'Black Forest Gummy Worms',
  'Black Forest Organic Gummies',
  'Black Gumballs',
  'Black Jack Gum',
  'Black Jelly Belly',
  'Black Licorice',
  'Black M&Ms',
  'Black Taffy',
  'Blood Candy',
  'Blue AirHeads',
  'Blue Candy',
  'Blue Candy Canes',
  'Blue Candy Sticks',
  'Blue Diamond',
  'Blue Dum Dums',
  'Blue Espeez',
  'Blue Gumballs',
  'Blue Hershey Kisses',
  'Blue Jelly Belly',
  'Blue Licorice',
  'Blue M&Ms',
  'Blue Raspberry AirHeads',
  'Blue Raspberry Dum Dums',
  'Blue Raspberry Licorice',
  'Blue Taffy',
  'Blueberry Candy',
  'Blueberry Dum Dums',
  'Bobs Candy Canes',
  'Bobs Sweet Stripes',
  'Bocadin',
  'Body Parts Candy',
  "Bogdon's",
  'Bon Bons',
  'Bone Shaped Candy',
  'Bonkers',
  'Bonomo Taffy',
  'Bonz',
  'Boogers',
  'Bosco',
  'Boston America Corp',
  'Boston Baked Beans',
  'Boston Fruit Slices',
  'Boston Warehouse Trading Corp',
  'Botan',
  'Bottle Caps',
  'Bounty',
  'Bourbon Candy',
  'Boy Baby Shower',
  'Boy Party',
  'Boyer Candy',
  "Brach's",
  "Brach's Bulk Candy",
  "Brach's Butterscotch",
  "Brach's Candy Canes",
  "Brach's Candy Corn",
  "Brach's Caramels",
  "Brach's Christmas Candy",
  "Brach's Cinnamon Candy",
  "Brach's Conversation Hearts",
  "Brach's Easter Candy",
  "Brach's Jelly Beans",
  "Brach's Jelly Nougats",
  "Brach's Royals",
  'Bradbury Barrel Company',
  'Brain Shaped Candy',
  'Breath Mints',
  'Brian Smillie',
  'Brittle Candy',
  'Broadway',
  'Brown Candy',
  'Brown Gumballs',
  'Brown Jelly Belly',
  'Brown Licorice',
  'Brown M&Ms',
  'Brown and Haley',
  'Brownie Brittle',
  'Bubbaloo',
  'Bubble Gum',
  'Bubble Gum Bulk',
  'Bubble Gum Cigars',
  'Bubble Gum Coins',
  'Bubble Gum Dum Dums',
  'Bubble Gum Machine',
  'Bubble Gum Tape',
  'Bubble Yum',
  'Bubblicious',
  'Bubu Lubu',
  'Buffet Kits',
  'Bug Shaped Candy',
  'Bulk Candy Bars',
  'Bulk Candy Canes',
  'Bulk Candy Corn',
  'Bulk Candy Favors',
  'Bulk Caramel Candy',
  'Bulk Christmas Candy',
  'Bulk Gumballs',
  'Bulk Licorice',
  'Bulk Lollipops',
  'Bulk M&Ms',
  'Bulk Mints',
  'Bulk Taffy',
  'Bulk Unwrapped Candy',
  'Bulk Wrapped Candy',
  'Bumplettes',
  'Bun',
  'Burger Shaped Candy',
  'Burton and Burton',
  'Butlers Chocolate',
  'Butter Candy',
  'Butter Mints',
  'Butter Rum Candy',
  'Butter Rum LifeSavers',
  'Butter Toffee',
  'Buttered Popcorn Jelly Belly',
  'Butterfields',
  'Butterfinger',
  'Butterfinger Candy Bar',
  'Butterfinger Cups',
  'Butterfly',
  'Butterfly Shaped Candy',
  'Buttermints',
  'Butterscotch Candy',
  'CB Stuffer',
  'CBD Candy',
  'CBD Gummies',
  'CBD Lollipops',
  'CHIPS',
  'Cadbury',
  'Caffarel',
  'Campfire',
  'Can You Imagine That Confections',
  'Canada Mints',
  'Canadian Candy',
  'Candy Bars',
  'Candy Blox',
  'Candy Bracelet',
  'Candy Buffet',
  'Candy Buttons',
  'Candy Canes',
  'Candy Cigarettes & Cigars',
  'Candy Clothing',
  'Candy Coated Licorice',
  'Candy Coated Popcorn',
  'Candy Corn',
  'Candy Corn Taffy',
  'Candy Earbuds',
  'Candy Fashion',
  'Candy Favors',
  'Candy Gifts',
  'Candy Jewelry',
  'Candy Machine',
  'Candy Melts',
  'Candy Necklace',
  'Candy Ornaments',
  'Candy People',
  'Candy Pillows',
  'Candy Planet',
  'Candy Props',
  'Candy Scoops, Jars, Bags, & Accessories',
  'Candy Sprinkles & Toppings',
  'Candy Sticks',
  'Candy Straws',
  'Candy Toys',
  'Candy Treasure',
  'Candy-Farm',
  'CandyRific',
  "Canel's",
  'Cape Cod Provisions',
  'Captain Morgan',
  'Car Shaped Candy',
  'Caramel Apple Candy',
  'Caramel Apple Dip',
  'Caramel Apple Pops',
  'Caramel Balls',
  'Caramel Candy',
  'Caramel Candy Bars',
  'Caramel Chewy Candy',
  'Caramel Creams',
  'Caramel Hard Candy',
  'Caramel M&Ms',
  'Caramel Popcorn',
  'Caramel Soft Candy',
  'Caramel Squares',
  'Caramello',
  'Caramels',
  'Carlos V',
  'Carnival',
  'Carousel',
  'Carrot Shaped Candy',
  'Cartoon',
  'Casali',
  'Cashews',
  'Casino',
  'Castle',
  'Cat Shaped Candy',
  'Cavendish and Harvey',
  'Cedrinca',
  "Cella's",
  'Chamoy Candy',
  'Champagne Candy',
  'Champagne Jelly Belly',
  'Charleston Chew',
  'Charms',
  'Charms Blow Pop',
  'Charms Blow Pop Minis',
  'Charms Giant Blow Pop',
  'Charms Lollipops',
  'Charms Mini Pops',
  'Charms Sour Balls',
  'Charms Squares',
  'Charms Super Blow Pop',
  'Charms Sweet Pops',
  'Charms Sweet and Sour Pops',
  'Charms Tear Jerker',
  'Chase Candy Company',
  'Cheong Woo Confectionery',
  'Cherry AirHeads',
  'Cherry Candy',
  'Cherry Dum Dums',
  'Cherry LifeSavers',
  'Cherry Mash',
  'Cherry Taffy',
  'Chewing Gum',
  'Chewy Candy',
  'Chick-O-Stick',
  'Chiclets',
  "Child's Play",
  'Chili Candy',
  'Chinese Candy',
  'Chinese New Year',
  'Chipurnoi',
  'Choc-Aid',
  'ChocOBeer',
  'Choco Rocks',
  'Choco Treasure',
  'Chocolate',
  'Chocolate Balls',
  'Chocolate Bars',
  'Chocolate Belgium',
  'Chocolate Bulk',
  'Chocolate Bunny',
  'Chocolate Candy',
  'Chocolate Candy Canes',
  'Chocolate Caramel Candy',
  'Chocolate Cars',
  'Chocolate Casino Chips',
  'Chocolate Casino Poker Chips',
  'Chocolate Chip Cookies',
  'Chocolate Chips',
  'Chocolate Chocolate',
  'Chocolate Cigars',
  'Chocolate Cluster',
  'Chocolate Coconut',
  'Chocolate Coins',
  'Chocolate Cookies',
  'Chocolate Covered Almonds',
  'Chocolate Covered Coffee Beans',
  'Chocolate Covered Cookies',
  'Chocolate Covered Espresso Beans',
  'Chocolate Covered Gummy Bears',
  'Chocolate Covered Marshmallows',
  'Chocolate Covered Nuts',
  'Chocolate Covered Peeps',
  'Chocolate Covered Pretzels',
  'Chocolate Covered Raisins',
  'Chocolate Covered Sunflower Seeds',
  'Chocolate Drops',
  'Chocolate Foiled Wrapped',
  'Chocolate Gourmet',
  'Chocolate Hearts',
  'Chocolate Individually Wrapped',
  'Chocolate Italian',
  'Chocolate Liquor',
  'Chocolate Malt Balls',
  'Chocolate Mexican',
  'Chocolate Mint Candy',
  'Chocolate Mints',
  'Chocolate Nougat',
  'Chocolate Roses',
  'Chocolate Squares',
  'Chocolate Sticks',
  'Chocolate Storybook',
  'Chocolate Taffy',
  'Chocolate Truffles',
  'Chocolate Turtles',
  'Chocolate With Nuts',
  'Chocolaterie Abtey',
  'Chocolates',
  'Chocwasabi',
  'Choice Confections',
  "Choward's",
  'Christmas',
  'Christmas Candy Canes',
  'Christmas Candy Gifts',
  'Christmas Chocolates',
  'Christmas Coal Candy',
  'Christmas M&Ms',
  'Christmas in July',
  'Chuckles',
  'Chunky',
  'Chupa Chups',
  'Cinco de Mayo',
  'Cinnamon Balls Candy',
  'Cinnamon Candy',
  'Cinnamon Chewy Candy',
  'Cinnamon Gummy Bears',
  'Cinnamon Hard Candy',
  'Cinnamon Hearts Candy',
  'Cinnamon Jelly Belly',
  'Cinnamon Mints Candy',
  'Cinnamon Ribbon Candy',
  'Circus',
  'Circus Peanuts Candy',
  'Claeys Candy',
  'Clark Bar',
  "Clark's Teaberry",
  'Classic Candy',
  'Classroom Exchange',
  'Cloetta',
  'Clove Gum',
  'Coal Candy',
  'Coconut Candy',
  'Coconut Candy Bars',
  'Coconut Patties',
  'Coffee & Tea Candy',
  'Coffee Crave',
  'Coffee Crisp',
  'Coffee Go',
  'Coffee Rio',
  'Coin Shaped Candy',
  'Cointreau',
  'Cola Candy',
  'Colombina',
  'Conagra',
  'Concord Confections',
  'Confiserie Heidel',
  'Construction',
  'Cookie Dough',
  'Cookies',
  'Corn Nuts',
  'Corrios',
  'Cotton Candy',
  'Cotton Candy Bags',
  'Cotton Candy Dum Dums',
  'Cotton Candy Jelly Belly ',
  'Cotton Candy Machine',
  'Cotton Candy Sugar',
  'Cotton Candy Taffy',
  'Country Time',
  'Cow Tales',
  'Cracker Jack',
  'Cranberry Candy',
  'Crayola',
  'Crayon',
  'Cream M&Ms',
  'Cream Soda Dum Dums',
  'Create A Treat',
  'Cremino',
  'Crispery',
  'Crows',
  'Crunch Bar',
  'Crunchie Bar',
  'Cry Baby',
  'Crystal Light',
  'Cube Shaped Candy',
  'Cucharita',
  'Cup-O-Gold',
  'Cups',
  'CurlyCutes',
  'DIY Candy Kits',
  'DOTS',
  "Dad's Root Beer",
  'Daily Chef',
  'Danish Candy',
  'Dark Blue M&Ms',
  'Dark Chocolate Candy',
  'Dark Chocolate Kit Kat',
  'Dark Chocolate M&Ms',
  'Dark Green M&Ms',
  'Dark Pink M&Ms',
  "DateMe's",
  'David Seeds',
  'Day of the Dead Candy',
  'DecoPac',
  'Dee Best',
  "Demet's Candy Company",
  'Dentyne',
  'Di Matteo Confetti',
  'Diamond Shaped Candy',
  'Dinosaur',
  'Dinosaur Shaped Candy',
  'Dippin Dots',
  'Discontinued Candy',
  'Dishes',
  'Disney',
  'Disney PEZ Dispensers',
  'Dog Shaped Candy',
  'Dolcetto Petites',
  'Dorval Trading',
  "Doscher's Candy Co",
  'Doublemint',
  'Dove Chocolate',
  'Dr Johns',
  'Drinking Straws',
  'Dryden & Palmer',
  'Dubble Bubble',
  'Dubble Bubble Baseball Bats',
  'Dubble Bubble Bucket',
  'Dubble Bubble Gum',
  'Dubble Bubble Gumball Machine',
  'Dubble Bubble Gumballs',
  'Dubble Bubble Pillow',
  'Dubble Bubble Sugar Free',
  'Dulces Liz',
  'Dulces Mara',
  'Dulces Pigui',
  'Dulces Tipicos',
  'Dum Dums',
  'Dum Dums Bulk',
  'Dum Dums Candy Canes',
  'Dum Dums Mega',
  'Dutch Licorice',
  'Duvalin',
  'Easter',
  'Easter Baskets',
  'Easter Candy Bulk ',
  'Easter Candy Eggs',
  'Easter Jelly Beans',
  'Eclipse',
  "Eda's",
  'Eddy Edibles',
  'Edradour',
  'Egg Hunt',
  'Egg Shaped Candy',
  'Eiffel Bon Bons',
  'El Bubble',
  'Electric Green M&Ms',
  'Elephant Shaped Candy',
  'Elmer Chocolate',
  'Emerald',
  "Emily's Chocolate",
  'Emoji',
  'Espeez Candy',
  'Espeez Cube Pops',
  'Espeez Rock Candy Crystal Sticks',
  'Extra',
  'Eyeball Shaped Candy',
  'Fall',
  'Famous Amos',
  'Famous Grouse',
  'Fancy Pops',
  'Farm',
  "Father's Day",
  'Favor Bags & Boxes',
  'Favor Sticks & Seals',
  'Favors',
  'Fazer',
  'Fazermint',
  'Ferndale Confectionery',
  'Ferrara Candy Company',
  'Ferrero',
  'Filled Licorice Candy',
  'Finders Keepers',
  'Fini',
  'Fish',
  'Fish Shaped Candy',
  'Fizzies',
  'Flake',
  'Flicks',
  'Flipsticks',
  'Flipz',
  'Flix Candy',
  'Floral Candy',
  'Flossugar',
  'Flower Shaped Candy',
  'Flowers',
  'Fluffy Stuff',
  'Flying Saucers',
  'Football',
  'Football Shaped Candy',
  'Ford Gum and Machine Co',
  'Foreign Candy Company',
  'Fort Knox',
  "Fralinger's",
  'Frankford Candy',
  'French Chew',
  'Frog Shaped Candy',
  'Frooties',
  'Frozen',
  'Fruit Assortments Candy',
  'Fruit Chew Pops',
  'Fruit Chews',
  'Fruit Drops',
  'Fruit Pastilles',
  'Fruit Shaped Candy',
  'Fruit Snacks',
  'Fruit Stripe',
  'Fruity Candy',
  'Fruzel',
  'Fun & Snack Size',
  'Fun Dip',
  'Fun Express',
  'Fun Size Candy',
  'Galaxy Bar',
  'Galerie',
  'Garden',
  'Garland Decorations',
  'Gelt Candy',
  'Gender Reveal',
  'Georgia Nut Company',
  'German Candy',
  'Gerrit J Verburg',
  'Gertrude Hawk',
  'Ghirardelli',
  'Ghirardelli Chocolate Caramel',
  'Ghirardelli Chocolate Squares',
  'Ghirardelli Dark Chocolate',
  'Ghirardelli Milk Chocolate',
  'Ghirardelli Peppermint Bark',
  'Giant & Big Candy',
  'Giant Candy Bars',
  'Giant Candy Cane',
  'Giant Candy Canes',
  'Giant Candy Tubes',
  'Giant Gummies',
  'Giant Gummy',
  'Giant Gummy Candy',
  'Giant Lollipops',
  'Giant PEZ Candy Dispenser',
  'Gifts',
  'Gilliam Candy',
  "Gimbal's Fine Candies",
  'Ginger Bites',
  'Ginger Candy',
  'Girl Baby Shower',
  'Girl Party',
  'Glee',
  'Glico',
  'Glitterati',
  'Glory Bee',
  'Gluten Free Candy',
  'Gluten Free Candy Bars',
  'Gluten Free Cotton Candy',
  'Go Organic',
  'GoLightly Candy',
  'Gobstopper',
  'Godinger',
  "Goetze's Candy Company",
  'Gold Candy',
  'Gold Hershey Kisses',
  'Gold M&Ms',
  'Gold Medal Products',
  'Goldkenn',
  'Golf',
  'Golf Ball Shaped Candy',
  'Goo Goo',
  'Goobers',
  'Good News Bar',
  'Good and Plenty',
  'Goody Good Stuff',
  'Gosanko Chocolate',
  'Gourmet International',
  'Graduation',
  'Grape AirHeads',
  'Grape Candy',
  'Grape Dum Dums',
  'Grape Licorice',
  'Grape Taffy',
  'Grapeheads',
  'Green Airheads',
  'Green Apple AirHeads',
  'Green Candy',
  'Green Candy Canes',
  'Green Candy Sticks',
  'Green Espeez',
  'Green Gumballs',
  'Green Hershey Kisses',
  'Green Jelly Belly',
  'Green Licorice',
  'Green M&Ms',
  'Grumpes',
  'Guava Candy',
  'Guinness',
  'Guittard Chocolate Company',
  'Gumball Machine Dispenser',
  'Gumballs',
  'Gumby',
  'Gumdrops',
  'Gummy',
  'Gummy Alligators',
  'Gummy Bands',
  'Gummy Bears',
  'Gummy Body Parts',
  'Gummy Brain',
  'Gummy Bunny',
  'Gummy Candy Corn',
  'Gummy Eyeballs',
  'Gummy Flowers',
  'Gummy Frogs',
  'Gummy Goods',
  'Gummy Hearts',
  'Gummy Lobsters',
  'Gummy Penguins',
  'Gummy Pigs',
  'Gummy Pizza',
  'Gummy Rats',
  'Gummy Rings',
  'Gummy Sharks',
  'Gummy Shotz',
  'Gummy Skeletons',
  'Gummy Skulls',
  'Gummy Snails',
  'Gummy Snakes',
  'Gummy Soda Bottles',
  'Gummy Spiders',
  'Gummy Teeth',
  'Gummy Worms',
  'Gusano',
  "Gustaf's Licorice",
  'Guylian',
  'HDS Trading Corp',
  'HOCH',
  'Halloween',
  'Halloween Candy Bulk',
  'Halloween Candy Color - Black',
  'Halloween Candy Color - Orange',
  'Halloween Candy Vegan',
  'Halloween Party Supplies',
  'Halloween Trick or Treat Candy',
  "Hammond's",
  'Hampton Farms',
  'Hanging Decorations',
  'Hanukkah',
  'Harcos Labs',
  'Hard Candy',
  'Hard Candy Bulk',
  'Hard Candy Tin',
  'Hard Licorice Candy',
  'Haribo',
  'Haribo Cherries',
  'Haribo Cola Bottles',
  'Haribo Dinosaurs',
  'Haribo Frogs',
  'Haribo Gold Bears',
  'Haribo Gummy Bears',
  'Haribo Licorice Wheels',
  'Haribo Smurfs',
  'Haribo Snakes',
  'Haribo Sour',
  'Haribo Sugar Free',
  'Harry London',
  'Harry Potter',
  'Harry and David',
  'Heart Shaped Candy',
  'Heath Bar',
  'Hello Kitty',
  'Hello Panda',
  'Hermann the German',
  'Hershey Chocolate',
  'Hershey Kisses',
  'Hershey Kisses Baby Shower',
  'Hershey Kisses Bulk',
  'Hershey Kisses Caramel',
  'Hershey Kisses Christmas',
  'Hershey Kisses Dark Chocolate',
  'Hershey Kisses Easter',
  'Hershey Kisses Giant',
  "Hershey Kisses Valentine's Day",
  'Hershey Kisses Wedding',
  'Hershey Kisses White Chocolate',
  'Hershey Kisses With Almonds',
  "Hershey's",
  "Hershey's With Almonds",
  'Hi-Chew',
  'Hickory Harvest',
  'Hillside Candy',
  'Hint Mint',
  'Home Essentials',
  'Honees',
  'Honey',
  'Honey Candy',
  'Honey Taffy',
  'Hopjes',
  'Horse Shaped Candy',
  'Hospitality Mints',
  'Hot Pink Candy',
  'Hot Pops',
  'Hot Tamales',
  'HotLix',
  'Hubba Bubba',
  'Hubba Bubba Bubble Tape',
  'Hubert',
  'HypnoPops',
  'I Want Candy',
  'IBC Root Beer',
  'ICEE',
  'Ice Breakers',
  'Ice Cream Candy',
  'Ice Cream Cone Shaped Candy',
  'Ice Cubes',
  'Iconic Candy Company',
  'Idaho Candy Company',
  'Idaho Spud',
  'Impact Confections',
  'In The Breeze',
  'Independent Can Company',
  'Insect & Arachnid',
  "It's a Boy Cigars",
  "It's a Girl Cigars",
  'Italian Candy',
  'JFC International',
  'JILA',
  'JOLS',
  "Jack Daniel's",
  'Jalapeno M&Ms',
  'James Candy Company',
  'Japanese Candy',
  'Japanese Kit Kat',
  'Jars',
  "Jasmine's",
  'Jaw Busters',
  'Jawbreaker Candy',
  'Jazzy Jewels',
  'Jelly Bean Dispenser',
  'Jelly Beans',
  'Jelly Belly',
  'Jelly Belly 4th of July',
  'Jelly Belly Alligators',
  'Jelly Belly Baby Shower',
  'Jelly Belly Bean Boozled',
  'Jelly Belly Bears',
  'Jelly Belly Birthday',
  'Jelly Belly Bulk',
  'Jelly Belly Bunnies',
  'Jelly Belly Candy Canes',
  'Jelly Belly Candy Corn',
  'Jelly Belly Chocolate',
  'Jelly Belly Christmas',
  'Jelly Belly Dinosaur',
  'Jelly Belly Easter',
  'Jelly Belly Frozen',
  'Jelly Belly Gifts',
  'Jelly Belly Gumdrops',
  'Jelly Belly Gummy',
  'Jelly Belly Halloween',
  'Jelly Belly Harry Potter',
  'Jelly Belly Hearts',
  'Jelly Belly Jawbreakers',
  'Jelly Belly Jelly Beans',
  'Jelly Belly Machine Dispenser',
  'Jelly Belly Organic',
  'Jelly Belly Pumpkins',
  'Jelly Belly Rats',
  'Jelly Belly Soda Bottles',
  'Jelly Belly Spider',
  'Jelly Belly Star Wars',
  'Jelly Belly Sugar Free',
  'Jelly Belly Superheroes',
  "Jelly Belly Valentine's Day",
  'Jelly Belly Wedding',
  'Jelly Candy',
  'Jerky',
  'Jim Beam',
  'Jolly Rancher',
  'Jolt',
  'Jones Soda',
  'Jooblers',
  'Jordan Almonds',
  'Jovy',
  'Joyva',
  'Jugos de Sabo',
  'Juicy Drop',
  'Juicy Fruit',
  'Jujubes',
  'Jujyfruits',
  'Jungle',
  'Junior Caramels',
  'Junior Mints',
  'Just Born Quality Confections',
  'Kabaya',
  'Kafe',
  'Kandi Jewelry',
  'Kane Candy',
  'Kanro',
  'Karla',
  'Karma Candy',
  'Kasugai',
  'Kawaguchi',
  "Kellogg's",
  'Kencraft Candy',
  'Kendon Candies',
  "Kenny's Candy Company",
  'Kervan USA',
  'Key Lime Candy',
  'Kidsmania',
  'Kimmie Candy Company',
  'Kinder',
  'King',
  'King Leo',
  'Kit Kat',
  'Kit Kat Christmas',
  'Kit Kat Easter',
  'Kit Kat Fun Size',
  'Kit Kat Halloween',
  'Kit Kat King Size',
  'Kits',
  "Koko's Confectionery",
  'Kookaburra',
  'Kopiko',
  'Koppers',
  'Korean Candy',
  'Kosher Bulk Candy',
  'Kosher Candy',
  'Kosher Chocolate',
  'Kosher Gumballs',
  'Kosher Gummy Candy',
  'Krackel Bar',
  'Kraft Foods',
  'Krinos',
  'Krispy Kreme Jelly Belly',
  'LICORETTE',
  'La Corona',
  'La Vie',
  'Labor Day',
  'Laffy Taffy',
  'Lake Country Candies',
  'Lammes Candies',
  'Lancaster Soft Cremes',
  'Large Gumball Machine With Stand',
  'Large Lollipops',
  'Lavender Espeez',
  'Le Grand Confectionary',
  'Leaf Brands',
  'Leaf Shaped Candy',
  'Lego Shaped Candy',
  'Lemon Candy',
  'Lemonhead',
  'Lerro',
  'Les Anis de Flavigny',
  'Licorice Bites',
  'Licorice Candy',
  'Licorice Gum',
  'Licorice Jelly Belly',
  'Licorice Laces',
  'Licorice Pipes Candy',
  'Licorice Ropes',
  'Licorice Sticks',
  'Licorice Twists',
  'Licorices',
  "Lieber's",
  'LifeSavers',
  'LifeSavers Big Ring Gummies',
  'LifeSavers Candy Books',
  'LifeSavers Candy Canes',
  'LifeSavers Gummies',
  'LifeSavers Sugar Free',
  'Light Blue Candy',
  'Light Blue M&Ms',
  'Light Pink Candy',
  'Light Purple M&Ms',
  'Likkebaard',
  'Lime Candy',
  "Linda's Lollies",
  'Lindt',
  'Lion',
  'Lion Bar',
  'Lip Pops',
  'Lip Shaped Candy',
  'Liqueur Fills',
  'Liquid & Spray Candy',
  'Liquor Candy',
  'Liquor Chocolates',
  'Liquor Filled Chocolate Bottles',
  'Liquor Gummy Bears',
  'Liquor Hard Candy',
  'Lobster Shaped Candy',
  'Locochas',
  'Lollipop Rings',
  'Lollipops & Suckers',
  'Long Boys',
  'Lonka',
  'Look!',
  'Lorena',
  'Luau',
  'Lucas Candy',
  'Lucky Country',
  'Ludo',
  'Lupy Lups',
  'Luvy Duvy',
  'M&M Shirts',
  "M&M's",
  'M&Ms Milk Chocolate',
  'Macadamias',
  'Madelaine Chocolate Advent Calendars',
  'Madelaine Chocolate Bunny',
  'Madelaine Chocolate Cigars',
  'Madelaine Chocolate Coins',
  'Madelaine Chocolate Company',
  'Madelaine Chocolate Fish',
  'Madelaine Chocolate Hearts',
  'Madelaine Chocolate Roses',
  'Madelaine Chocolate Stars',
  'Madelaine Chocolate Turkeys',
  'Madelaine Christmas Candy',
  'Madelaine Duets',
  'Madelaine Halloween Candy',
  "Maker's Mark",
  'Mallo Cup',
  'Malt Balls',
  'Maltesers',
  'Mama Mellace',
  'Mamba',
  'Mango Candy',
  'Maple Taffy',
  'Mardi Gras',
  'Marich Caramel Candy',
  'Marich Christmas Candy',
  'Marich Confectionery',
  'Marich Dark Chocolate',
  'Marich Gummy Candy',
  'Marich Halloween Candy',
  'Marich Jordan Almonds',
  'Marich Licorice',
  'Marich Milk Chocolate',
  'Marich Organic Candy',
  'Marich Peanut Butter Candy',
  'Marich Toffee Candy',
  "Marich Valentine's Day Candy",
  'Maroon M&Ms',
  'Mars Inc',
  'Marshmallow Candy',
  'Marshmallow Castle',
  'Marshmallow Circus Peanuts',
  'Marshmallow Cone Company',
  'Marshmallow Fun',
  'Marshmallows',
  'Marukawa',
  'Mary Jane',
  'Matchems',
  "McCraw's Taffy",
  'McKeever and Danlee',
  "McSteven's",
  'Medical',
  'Mega Candy',
  'Meiji',
  'Mellowcreme',
  'Melster Candies',
  'Memorial Day',
  'Mentos',
  'Mexican Candy',
  'Mexican Candy Bags',
  'Mexican Coconut Candy',
  'Mexican Peanut Candy',
  'Mexican Pinata Candy',
  'Mexican Tamarind Candy',
  'Mickey Mouse Shaped Candy',
  "Midway's Finest",
  'Mighty Malts',
  'Mike and Ike',
  'Milk Chocolate Candy',
  'Milk Chocolate Kit Kat',
  'Milk Duds',
  'Milkfuls',
  'Milky Way',
  'Mini & Small Candy',
  'Mini Candy Canes',
  'Mini Gumball Machine Favor',
  'Mini Gumballs',
  'Mini M&Ms',
  'Mini Q',
  'Minis & Miniatures',
  'Mint Candy',
  'Mint Chocolate Candy',
  'Mint Julep',
  'Mint Patties',
  'Mints',
  'Molasses Taffy',
  'Mondelez International',
  'Money',
  'Monkey Shaped Candy',
  'Monster Shaped Candy',
  'Montes',
  'Moon Pie',
  'Moon Shaped Candy',
  'Moose Munch',
  'Morris National Inc',
  "Mother's Day",
  'Mounds',
  'Mount Franklin Foods',
  'Mountain Bar',
  'Mountain Thins',
  'Movie Theater Candy',
  'Mr Goodbar',
  'Muddy Bears',
  'Muecas',
  'Munch Bar',
  'Mustache Shaped Candy',
  'Mystery Flavor AirHeads',
  'Nassau Candy',
  'Naturally Nutfull',
  'Navy Blue Candy',
  'Necco',
  'Necco Wafers',
  'Nerds',
  'Nerds Chewy',
  'Nerds Christmas',
  'Nerds Mini Boxes',
  'Nerds Pillows',
  'Nerds Rainbow',
  'Nerds Rope',
  "Nerds Valentine's Day",
  'Nestle',
  "New Year's Eve",
  'Newblers',
  'Nickelodeon',
  'Nik-L-Nip',
  'Nonpareil Candy',
  'Nordic Sweets',
  'Nostalgia Electrics',
  'Nostalgic Candy',
  'Nougat',
  'Novelty Candy',
  'Novelty Toys',
  'Novelty and Gifts',
  'Now and Later',
  'Nut Goodies',
  'Nut Warehouse',
  "Nut'n But Natural",
  'Nutella',
  'Nutresa',
  'Nutri Grain',
  'Nuts',
  'Ocean',
  'Octopus Shaped Candy',
  'Office Candy',
  'Oh Henry',
  'Oh Poop',
  "Oh Ryan's",
  'Oinks',
  'Old Faithful',
  'Old Fashioned Candy & Retro Sweets',
  'Old Fashioned Candy Bars',
  'Old Fashioned Candy Sticks',
  'Old Fashioned Penny Candy',
  'Old Fashioned Rock Candy',
  'Old Fashioned Taffy',
  'Old Trapper',
  'Orange AirHeads',
  'Orange Candy',
  'Orange Candy Sticks',
  'Orange Dum Dums',
  'Orange Espeez',
  'Orange Hershey Kisses',
  'Orange Jelly Belly',
  'Orange Licorice',
  'Orange M&Ms',
  'Orange Shaped Candy',
  'Orange Taffy',
  'Orbit',
  'Oreo',
  'Organic Candy',
  'Organic Gummies',
  'Original Gourmet Food Company',
  'Orville Redenbacher',
  'Owl Shaped Candy',
  'PEZ',
  'PJ Masks',
  'Paleton',
  'Palm Oil Free Candy',
  'Party Balloons',
  'Party Darby',
  'Party Favor Assortments',
  'Party Supplies',
  'Party Sweets',
  'Pastel Candy',
  'Pastiglie Leone',
  'Paw Patrol',
  'PayDay',
  'Peach Candy',
  'Peanut Butter Bars',
  'Peanut Butter Candy',
  'Peanut Butter Chocolate Candy',
  'Peanut Butter M&Ms',
  'Peanut Butter Taffy',
  'Peanut Candy',
  'Peanut Chews',
  'Peanut Free Candy',
  'Peanut M&Ms',
  'Peanuts',
  'Pearl M&Ms',
  'Pearls Candy',
  "Pearson's Candy Company",
  'Pecans',
  'Pecositas',
  'Peeps',
  'Pelon Pelo Rico',
  'Penguin Shaped Candy',
  'Peppa Pig',
  'Peppermint Candy',
  'Peppermint Candy Cane',
  'Peppermint LifeSavers',
  'Peppermint Taffy',
  'Perfect Man',
  'Perfetti Van Melle',
  'Perugina',
  'Petite Deceit',
  'Pica Limon',
  'Pig Shaped Candy',
  'Pillow Mints',
  'Pinata',
  'Pinata Candy',
  'Pinatas',
  'Pine Ame',
  'Pineapple Candy',
  'Pineapple Shaped Candy',
  'Pink Cadillacs',
  'Pink Candy',
  'Pink Candy Sticks',
  'Pink Dum Dums',
  'Pink Espeez',
  'Pink Gumballs',
  'Pink Hershey Kisses',
  'Pink Jelly Belly',
  'Pink Lemonade AirHeads',
  'Pink M&Ms',
  'Pink Taffy',
  'Pink and Gold Candy',
  'Pinwheel Candy Mints',
  'Pirate',
  'Pistachios',
  'Pixy Stix',
  'Pizza Shaped Candy',
  'Plantation Candies',
  'Planters',
  'Platinum M&Ms',
  'Pocky',
  'Pooping Candy',
  'Pop Rocks',
  'Pop Tarts',
  'Pop Ups',
  'Popcorn',
  'Popcornopolis',
  'Powder & Particle Candy',
  "President's Day",
  'Pretzel M&Ms',
  'Pretzels',
  'Primrose Candy Company',
  'Princess',
  'Prisma Mexico',
  'Productos Indy',
  'Prosecco Candy',
  'Puchao',
  'Pucker Powder',
  'Pufflettes',
  'Puffy Poles',
  'Pumpkin Seeds',
  'Pumpkin Shaped Candy',
  'Pumpkin Spice',
  'Puntini',
  'Purple AirHeads',
  'Purple Candy',
  'Purple Candy Canes',
  'Purple Candy Sticks',
  'Purple Espeez',
  'Purple Gumballs',
  'Purple Hershey Kisses',
  'Purple Jelly Belly',
  'Purple Licorice',
  'Purple M&Ms',
  'Purple Taffy',
  'Push Pop',
  'Quality Candy',
  'Quality Candy Company',
  'Quality Sticks',
  'Quinceanera',
  'R.M. Palmer Company',
  "RJ's Licorice",
  'Raffaello',
  'Rainbow Candy',
  'Rainbow Candy Cane',
  'Rainbow Gumballs',
  'Rainbow Lollipops',
  'Raindrops',
  'Raisinets',
  'Raisins Candy',
  'Rascals',
  'Raspberry Candy',
  'Ratliff Candy Company',
  'Razzles',
  'Real Licorice',
  'Rebanaditas',
  'Reber Chocolate',
  'Red AirHeads',
  'Red Bird',
  'Red Candy',
  'Red Candy Sticks',
  'Red Espeez',
  'Red Gumballs',
  'Red Hershey Kisses',
  'Red Hots',
  'Red Jawbreakers',
  'Red Jelly Belly',
  'Red Licorice',
  'Red M&Ms',
  'Red Vines',
  'Red White and Blue Candy',
  'Red White and Blue Gumballs',
  'Red White and Blue M&Ms',
  "Reed's",
  "Reese's",
  'Regal Crown',
  'Rellerindos',
  'Remy Martin',
  'Rendez Vous',
  'Ribbon Candy',
  'Ribon',
  'Rice Crispy Treats',
  'Rice Krispies',
  'Richardson Brands',
  'Ricola',
  'Ricolino',
  'Riesen',
  'Ring Pop',
  'Rip Rolls',
  'Ritter Sport',
  'Roca Thins',
  'Rocher',
  'Rock Candy',
  'Rock Candy Crystals',
  'Rock Candy Sticks',
  'Rock Candy Strings',
  'Rockaleta',
  'Rocky Road',
  'Rolla Roaster',
  'Rolo',
  'Root Beer Candy',
  'Root Beer Dum Dums',
  'Rose Flavored Candy',
  'Rose Shaped Candy',
  'Royal Blue Candy',
  'Royal Family Foods',
  'Rum Candy',
  'Runk Candy Company',
  'Runts',
  'Russell Stover',
  'Saf-T-Pops',
  "Saint Patrick's Day",
  'Sale',
  'Salt Water Taffy',
  'Salted Caramel Candy',
  'Salted Nut Roll',
  'Salty Licorice',
  'Saratoga Sweets',
  'Sassy Cylinders',
  'Sassy Sours',
  'Sassy Spheres',
  'Sassy Straws',
  'Satellite Wafers',
  'Schladerer',
  'Schluckwerder',
  'Sconza Candy',
  'Scoops',
  'Sea Salt Chocolate Candy',
  'Seashell Shaped Candies',
  'Seattle Chocolate Company',
  'Seeds',
  'Seneca',
  'Senjaku',
  'Sephra',
  "Sevigny's",
  'Sezme',
  'Shark',
  'Shark Shaped Candy',
  'Silver Candy',
  'Silver Hershey Kisses',
  'Silver M&Ms',
  'Sin City Suckers',
  'Sixlets',
  'Skittles',
  'Skittles Bulk',
  'Skittles Christmas',
  'Skittles Easter',
  'Skittles Halloween',
  'Skittles Sour',
  "Skittles Valentine's Day",
  'Skor',
  'Skull Shaped Candy',
  'Sky Bar',
  'Slap Stix',
  'Slim Jim',
  'Slime Candy',
  'Slo Poke',
  'Slush Puppie',
  'Small Gumball Machine',
  'Small Lollipops',
  'Smarties',
  'Smores Candy',
  'Snacks',
  'Snake Shaped Candy',
  'Snappers',
  'Snickers',
  'Snickers Almond',
  'Snickers Bar Giant',
  'Snickers Candy Bars',
  'Snickers Dark Chocolate',
  'Snickers Fun Size',
  'Snickers King Size',
  'Snickers Minis',
  'Snickers Peanut Butter',
  'Soccer',
  'Soccer Ball Shaped Candy',
  'Soda Candy',
  'Sonrics',
  'Sophie Mae',
  'Sorbee',
  'Sour Apple Dum Dums',
  'Sour Balls Candy',
  'Sour Belts Candy',
  'Sour Candy',
  'Sour Chewy Candy',
  'Sour Gummies',
  'Sour Gummy Candy',
  'Sour Hard Candy',
  'Sour Jelly Belly',
  'Sour Patch Kids',
  'Sour Powder Candy',
  'Sour Power',
  'Sour Power Belts',
  'Sour Power Straws',
  'Sour Punch',
  'Sour Punch Straws',
  'Sour Punch Twists',
  'Sour Rope Candy',
  'Sour Spray Candy',
  'Sour Straws Candy',
  'Space',
  'Space Ship Shaped Candy',
  'Spangler',
  'Spangler Candy Canes',
  'Spearmint',
  'Spearmint Candy',
  'Spearmint LifeSavers',
  'Special K',
  'Sphere Shaped Candy',
  'Spicy Candy',
  'Spicy Cinnamon Candy',
  'Spicy Mango Candy',
  'Spicy Mexican Candy',
  'Spicy Tamarind Candy',
  'Spider',
  'Spider Shaped Candy',
  'Spiderman',
  'Spinners',
  'Spongebob',
  'Sports',
  'Sports Shaped Candy',
  'Spreads',
  'Spree',
  'Sprinkle King',
  'Squeeze Candy',
  'Squiggly Pops',
  'Squire Boone Village',
  'Star Shaped Candy',
  'Star Wars',
  'Star Wars PEZ Dispensers',
  'Starbucks',
  'Starburst',
  'Starfish Shaped Candy',
  'Starlight Mints',
  'Stewart Candy Company',
  'Stichler Products',
  'Stick Mints',
  'Sticklettes',
  'Stocking Stuffers',
  'Storck',
  'Storz Schokolade',
  'Strawberry AirHeads',
  'Strawberry Candy',
  'Strawberry Gummies',
  'Strawberry Hill',
  'Strawberry Kit Kat ',
  'Strawberry Shaped Candy',
  'Strawberry Taffy',
  'String Licorice Candy',
  'Sugar Babies Candy',
  'Sugar Daddy Candy',
  'Sugar Free Black Licorice',
  'Sugar Free Bulk',
  'Sugar Free Candy',
  'Sugar Free Caramel',
  'Sugar Free Chocolate',
  'Sugar Free Chocolate Bars',
  'Sugar Free Cinnamon Candy',
  'Sugar Free Gum',
  'Sugar Free Gumballs',
  'Sugar Free Gummy Bears',
  'Sugar Free Hard Candy',
  'Sugar Free Jelly Beans',
  'Sugar Free Lemon Drops',
  'Sugar Free Licorice',
  'Sugar Free Lollipops',
  'Sugar Free Mints',
  'Sugar Free Rootbeer Barrels',
  'Sugar Free Sour Candy',
  'Sugar Free Taffy',
  'Summer',
  'Sun Maid',
  'Sunbursts Candy',
  'Sunflower Food Company',
  'Sunflower Seeds',
  'Sunkist',
  'Sunny Seeds',
  'Sunrise Confections',
  'Super Bubble',
  'Superhero',
  'Superior Chocolate',
  'Supreme Chocolatier',
  'Surf Sweets',
  'Sushi Candy',
  'Sushi Shaped Candy',
  'Swedish Candy',
  'Swedish Fish',
  'SweeTARTS',
  'Sweet Candy Company',
  'Sweet Maple Candies',
  'Sweet N Fun',
  'Sweet Nature Candy Canes',
  'Sweet Shots',
  'Sweet Spindles',
  'Sweet Tarts Candy',
  'Sweet Treats',
  'SweetWorks',
  'Sweethearts',
  'Sweets Indeed',
  'Swipple Pops',
  'Swirl Lollipops',
  'Swirl Pops',
  'Swiss Miss',
  "Switzer's Candy Company",
  'Swizzle Sticks',
  'Tabasco',
  'Table Covers',
  'Taffy',
  'Taffy Town',
  'Take 5 Candy',
  'Tamago',
  'Tamarind Candy',
  'Tangy Zangy',
  'Tart n Tinys',
  'Taste of Nature',
  'Tastebuds Popcorn',
  'Teal M&Ms',
  'Teenee Beanee',
  'Temkin International',
  'Tequila Candy',
  "Terry's Chocolate Orange",
  'Tesla Pops',
  'Thank You',
  'Thanksgiving',
  'The Hershey Company',
  'Thin Mints',
  'Thompson Chocolate',
  'Tic Tac',
  'Tiny Candy Hearts',
  'Toblerone',
  'Toffee Candy',
  'Toffee Crisp',
  'Toffifay',
  'Tombstone Shaped Candy',
  'Tongs',
  'Too Tarts',
  'Tool Shaped Candy',
  'Tooth Shaped Candy',
  'Tootsie Pops',
  'Tootsie Roll',
  'Tootsie Roll Industries',
  'Top Pops',
  'Topps',
  'Torie and Howard',
  'Toxic Waste Candy',
  'Toysmith',
  'Toyz N Treatz',
  'Trail Mix',
  'Train Shaped Candy',
  'Treat Street',
  'Trefin',
  'Triangular Shaped Candy',
  'Trident',
  'Trolli',
  'Trolli Sour Brite Crawlers',
  'Tropical Candy',
  'TruJoy Sweets',
  'TrueNorth',
  'Truffettes de France',
  'Turin Chocolate',
  'Turkey Shaped Candy',
  'Turkish Candy',
  'Turkish Taffy',
  'Turquoise Blue Candy',
  'Turtle Shaped Candy',
  'Turtles Candy',
  'Tutti Fruitti Jelly Belly',
  'Twin Bing',
  'Twinkle Candy',
  'Twirl Pops',
  'Twix',
  'Twizzlers',
  'UK Candy',
  'UNO',
  'Unicorn',
  'Unicorn Pops',
  'Unlimited Containers',
  'Urine Candy',
  "Valentine's Day",
  'Valentines Day Candy Bouquets',
  'Valentines Day Candy Bulk',
  'Valentines Day Candy Gifts',
  'Valentines Day Candy Hearts',
  'Valentines Day Chocolates',
  'Valentines Day Gumballs',
  'Valentines Day Gummy',
  'Valentines Day Jelly Beans',
  'Valentines Day Lollipops & Suckers',
  'Valentines Day Marshmallows',
  'Valentines Day Sprinkles',
  'Valomilk',
  'Vanilla Candy',
  'Vanilla Taffy',
  'Vegan Candy',
  'Vegas Image',
  'Vegetable Shaped Candy',
  'Vending Machine Candy',
  'Vermont Christmas Company',
  'Vero',
  'Very Cherry Jelly Belly',
  'Very Special Chocolates',
  'Vickerman',
  'Victorinox',
  'Vidal Candies',
  'Vienna',
  'Vintage Bubble Gum Machine',
  'Vintage Gum',
  'Violet Candy',
  'Violet Crumble',
  'Vodka Candy',
  'Wacky Wafers',
  'Wafers',
  "Walker's Nonsuch",
  'Walnettos',
  'Walnuts',
  'WarHeads',
  'WarHeads Candy Canes',
  'WarHeads Chewy Cubes',
  'WarHeads Easter',
  'WarHeads Extreme Sour',
  'WarHeads Hard Candy',
  'WarHeads Spray',
  'WarHeads Worms',
  'Warrell',
  'Watermelon AirHeads',
  'Watermelon Candy',
  'Watermelon Licorice',
  'Watermelon Shaped Candy',
  'Watermelon Taffy',
  'Wax Bottles',
  'Wax Candy',
  'Wax Lips',
  'Wazoo Bar',
  'Wedding',
  'Wedding Blend M&Ms',
  'Wedding Chocolate Flowers',
  'Wedding Jordan Almonds',
  'Wedding Mints',
  "Welch's",
  "Werther's Original",
  'Whatchamacallit',
  'Whirly Pop',
  'Whiskey Candy',
  'White AirHeads',
  'White Candy',
  'White Candy Sticks',
  'White Chocolate Candy',
  'White Chocolate Kit Kat',
  'White Espeez',
  'White Gumballs',
  'White Hershey Kisses',
  'White Jelly Belly',
  'White M&Ms',
  'White Wedding',
  'Whoppers',
  'Wild West Pops',
  'WildRoots Foods',
  'Williams Bennett',
  'Wilton',
  'Windel',
  'Winterfresh Gum',
  'Wintergreen LifeSavers',
  'Wintergreen Mint Candy',
  'Wonderful Pistachios',
  'Wonka Candy',
  'World Confections',
  'Worm Shaped Candy',
  'Wrapped Candy Canes',
  'Wrapped Gumballs',
  'Wrapped Licorice Candy',
  'Wrapped Twizzlers',
  'Yellow Candy',
  'Yellow Candy Sticks',
  'Yellow Espeez',
  'Yellow Gumballs',
  'Yellow M&Ms',
  'YooHoo',
  'York Peppermint Patties',
  'Yowie',
  'Yum Yum',
  'YumEarth',
  'YumJunkie',
  'Yumy Yumy',
  'Zachary',
  'Zagnut',
  'Zaza',
  'Zazers',
  'Zero Bar',
  'Zollipops',
  'ZotZ',
  'de la Rosa',
  'e-ma',
  'eFrutti',
]
